project:
  type: website
  output-dir: _site

website:
  title: "How To Train Your Researcher"
  site-url: https://how-to-train-your-researcher.github.io/HTTYR
  description: "Open-source advice for entering AI research."
  navbar:
    left:
      - href: advice/httyr.qmd
        text: HTTYR
      - href: advice/orv.qmd
        text: ORV
      - href: advice/sss-content.qmd
        text: SSS
  repo-url: https://github.com/How-To-Train-Your-Researcher/HTTYR
  repo-actions: [edit, issue]

language:
  title-block-published: "Updated"
  title-block-author-single: "Authors"
  title-block-author-plural: "Authors"

bibliography: references.bib
csl: https://www.zotero.org/styles/ieee

format:
  html:
    theme: Flatly
    toc: true
    toc-depth: 3
    code-copy: true

editor:
  render-on-save: true